"""
Django settings for eterpoetic project.

Generated by 'django-admin startproject' using Django 4.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import sys
from django.contrib.messages import constants as messages
import dj_database_url
from django.utils.translation import gettext_lazy as _
from dotenv import load_dotenv  # pip install python-dotenv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
TEMPLATES_DIR = os.path.join(BASE_DIR, 'templates')

# Local-only helpers: load .env or env.py if present (won't exist on Heroku)
load_dotenv(BASE_DIR / ".env")
if (BASE_DIR / "env.py").exists():
    sys.path.append(str(BASE_DIR))
    import env  # sets os.environ[...] locally


def env_required(name: str) -> str:
    v = os.environ.get(name)
    if not v:
        raise RuntimeError(f"Missing required env var: {name}")
    return v


# --- Core settings ---
# SECRET_KEY must be read from environment variable
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# DEBUG = os.environ.get("DEBUG", "False") == "True"

# ALLOWED_HOSTS for production (when DEBUG is False)

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    "dev.local",
    '[::1]',
    '.herokuapp.com',
    'eterpoetic-62a49da213d8.herokuapp.com',
    '*.codeinstitute-ide.net',
    '*.githubpreview.dev',
]
# Add hostnames from the environment if present
hostnames = os.environ.get('ALLOWED_HOSTS', '').split(',')
ALLOWED_HOSTS.extend([h for h in hostnames if h])

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'django.contrib.sites',  # Uncomment if using allauth with sites framework
    'django_summernote',
    # cloudinary
    'cloudinary_storage',
    'cloudinary',
    # allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',
    # 'allauth.socialaccount.providers.instagram',

    # crispy
    'crispy_forms',
    'crispy_bootstrap5',
    # ----------
    # 'sslserver',
    'core',
    'facebook_integration',

    'blog',
    'about',
    'poetry',
]

# Note: A redundant AUTHENTICATION_BACKENDS definition was removed from here.
# The active definition is near the end of the file.

SITE_ID = 1
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = "eterpoetic.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [TEMPLATES_DIR],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

TEMPLATES[0]["DIRS"] = [BASE_DIR / "templates"]

WSGI_APPLICATION = "eterpoetic.wsgi.application"

# --- Database: robust local/Heroku + safe tests ---
DEFAULT_SQLITE_PATH = BASE_DIR / "db.sqlite3"

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": DEFAULT_SQLITE_PATH,
    }
}

DATABASE_URL = os.environ.get("DATABASE_URL")
if DATABASE_URL:
    # Parse Heroku/ElephantSQL URL
    DATABASES["default"] = dj_database_url.parse(
        DATABASE_URL, conn_max_age=600
    )

    # Only keep SSL options for Postgres
    engine = DATABASES["default"].get("ENGINE", "")
    if "postgresql" in engine:
        opts = DATABASES["default"].get("OPTIONS", {}) or {}
        opts.setdefault("sslmode", "require")
        DATABASES["default"]["OPTIONS"] = opts
    else:
        DATABASES["default"].pop("OPTIONS", None)

# Use a clean SQLite DB when running tests (no Postgres-only OPTIONS)
if any(arg.startswith("test") for arg in sys.argv):
    DATABASES["default"] = {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": ":memory:",              # or BASE_DIR / "test_db.sqlite3"
    }


# CSRF (no trailing slashes)
CSRF_TRUSTED_ORIGINS = [
    "http://127.0.0.1:8000",
    "http://localhost:8000",
    "http://dev.local:8000",
    "https://*.herokuapp.com",
    "https://eterpoetic-62a49da213d8.herokuapp.com",
    "https://*.codeinstitute-ide.net",
    "https://*.githubpreview.dev",
]

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation."
                "UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation."
                "MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation."
                "CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation."
                "NumericPasswordValidator",
    },
]

# Crispy Forms Settings
# ---------------------
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

LANGUAGES = [
    ('en', _('English')),
    ('es', _('Spanish')),
    ('fr', _('French')),
    # add others as needed
]

TIME_ZONE = "UTC"

USE_I18N = True
USE_L10N = True
USE_TZ = True

LOCALE_PATHS = [
    BASE_DIR / "locale",  # Django needed for translation (.po/.mo)
]

# Static / Media files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
STATIC_URL = "/static/"
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = (
    "whitenoise.storage.CompressedManifestStaticFilesStorage"
)

# Media via Cloudinary (only if you have CLOUDINARY_URL on Heroku)
if os.environ.get("CLOUDINARY_URL"):
    DEFAULT_FILE_STORAGE = "cloudinary_storage.storage.MediaCloudinaryStorage"

# Tell Cloudinary to always use secure HTTPS URLs
CLOUDINARY = {
    'secure': True
}

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ----------------------------------------------------------------------
# CONDITIONAL PRODUCTION SETTINGS (Applied when DEBUG is False/empty)
# ----------------------------------------------------------------------

# if DEBUG:
#     # Dev: HTTP only
#     SECURE_SSL_REDIRECT = False
#     SESSION_COOKIE_SECURE = False
#     CSRF_COOKIE_SECURE = False
#     SECURE_HSTS_SECONDS = 0
# else:
#     # Prod: enforce HTTPS + secure cookies
#     SECURE_SSL_REDIRECT = True
#     SESSION_COOKIE_SECURE = True
#     CSRF_COOKIE_SECURE = True
#     SECURE_HSTS_SECONDS = 31536000
#     SECURE_HSTS_INCLUDE_SUBDOMAINS = True
#     SECURE_HSTS_PRELOAD = True

MESSAGE_TAGS = {
    messages.SUCCESS: 'alert-success',
    messages.ERROR: 'alert-danger',
}

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

SITE_ID = 1
LOGIN_REDIRECT_URL = "/"
ACCOUNT_LOGOUT_REDIRECT_URL = "/"


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST')
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL')


# --- Allauth v0.65+ (new-style settings) ---

# What credentials are allowed at login:
# choose {"email"} if you don't want username logins.
ACCOUNT_LOGIN_METHODS = {"username", "email"}

# Which fields appear on the signup form and which are required (*):
# remove "username*" if you don't want usernames at all.
ACCOUNT_SIGNUP_FIELDS = ["email*", "username*", "password1*", "password2*"]

# Email verification policy still uses the same name:
ACCOUNT_EMAIL_VERIFICATION = "none"   # or "optional" / "mandatory"

# Custom social account adapter to enable auto-signup when email is provided
SOCIALACCOUNT_ADAPTER = "core.adapters.AutoSignupWithEmailAdapter"

# Social helpers
SOCIALACCOUNT_QUERY_EMAIL = True
# IMPORTANT: automatically log in users after social signup
SOCIALACCOUNT_LOGIN_ON_GET = True


SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": ["profile", "email"],
        "APP": {
            "client_id": os.environ.get("GOOGLE_CLIENT_ID"),
            "secret": os.environ.get("GOOGLE_CLIENT_SECRET"),
            "key": "",
        },
    },
    "facebook": {
        "APP": {
            "client_id": os.environ.get("FACEBOOK_APP_ID"),
            "secret": os.environ.get("FACEBOOK_APP_SECRET"),
            "key": "",
        },
        # Optional but fine:
        "SCOPE": ["public_profile", "email"],  # no review required
        # ensures email is requested
        "FIELDS": [
            "id",
            "email",
            "name",
            "first_name",
            "last_name"
        ],
    },
}
