# Generated by Django 5.2.7 on 2025-11-03 03:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("poetry", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="poem",
            name="featured_image",
            field=cloudinary.models.CloudinaryField(
                default="placeholder", max_length=255, verbose_name="image"
            ),
        ),
    ]
