# Generated by Django 5.2.7 on 2025-11-03 04:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("poetry", "0002_poem_featured_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poem",
            name="featured_image",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                default="default_poem_img",
                max_length=255,
                null=True,
                verbose_name="image",
            ),
        ),
    ]
