# Generated by Django 5.2.7 on 2025-11-03 05:05

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("poetry", "0003_alter_poem_featured_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poem",
            name="featured_image",
            field=cloudinary.models.CloudinaryField(
                default="placeholder", max_length=255, verbose_name="image"
            ),
        ),
    ]
