# Generated by Django 5.2.7 on 2025-11-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poetry", "0004_alter_poem_featured_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
