# Generated by Django 5.2.7 on 2025-11-04 18:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("poetry", "0005_alter_collection_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="collection_image",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                default="placeholder",
                max_length=255,
                null=True,
                verbose_name="collection_image",
            ),
        ),
    ]
