# Generated by Django 5.2.7 on 2025-11-15 01:03

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("poetry", "0007_poem_favorites"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="photo",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                default="placeholder_author",
                max_length=255,
                null=True,
                verbose_name="author_photo",
            ),
        ),
    ]
